### ISSUE TITLE
Metadata string values are quoted.

### ISSUE THREAD

**Issue by pms1969** [mockersf/concourse-resource-rs#3]
It's trivial, but metadata string values have quotes when output.
i.e. 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/2762128/151356183-aca6242d-1318-44af-aa1d-19fbaa82bacc.png">
What I would prefer to see is:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/2762128/151356299-59fabb57-b74c-4c1f-b1dd-90d32df59254.png">

I've figured out what needs to be done, although I'm not sure if it's optimal, would you be open to a PR?

Also, thanks for the project.  Saved me a tonne of time.

**Comment by mockersf** [comment]
yes please, a PR would be most welcome!

**Comment by pms1969** [comment]
Would you be so kind as to make another release with that change?? :)

**Comment by mockersf** [comment]
Sorry, I wanted to take the time to test it on a concourse instance but didn't have the time. It's released now!

**Comment by pms1969** [comment]
❤️ 👍
